//! Per-stage oracles (mission plan §2): each net must reproduce its PyTorch
//! reference on a pinned fixture — CRAFT to numeric tolerance on the
//! region/affinity maps, CRNN to exact CTC ids.
//!
//! Fixtures are regenerated by `tools/carmenta_m_c1_prepare.py` and
//! `tools/carmenta_crnn_prepare.py`; weights are the converted safetensors in
//! the FFai cache. Both are fetched/derived artifacts, so these tests SKIP
//! (loudly) when they're absent rather than failing a fresh checkout —
//! the bench gates, not CI, are where absence would be dishonest.

use candle_core::{DType, Device, Tensor};
use candle_nn::VarBuilder;
use std::path::PathBuf;

fn fixtures() -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("../../corpora/refs/fixtures")
}

fn model_file(model: &str, file: &str) -> Option<PathBuf> {
    let p = ffai_models::cache_dir().join("models").join(model).join(file);
    p.exists().then_some(p)
}

#[test]
fn craft_maps_match_pytorch_reference() {
    let crop_png = fixtures().join("craft_crop.png");
    let maps_bin = fixtures().join("craft_maps_320x320x2_f32.bin");
    let Some(weights) = model_file("craft-mlt", "craft.safetensors") else {
        eprintln!("SKIP craft oracle: weights not in cache (run tools/carmenta_m_c1_prepare.py)");
        return;
    };
    if !crop_png.exists() || !maps_bin.exists() {
        eprintln!("SKIP craft oracle: fixtures missing (run tools/carmenta_m_c1_prepare.py)");
        return;
    }

    let img = ffai_media::load_image(&crop_png).expect("fixture crop loads");
    assert_eq!((img.width, img.height), (640, 640));
    let gray = ffai_carmenta::image::to_gray_f32(&img).unwrap();
    // Scale pinned at 1.0 EXPLICITLY: this oracle tests the network against
    // its fixture, and must not move when the detection scaling policy does.
    let (input, scale) =
        ffai_carmenta::image::craft_input_scaled(&gray, 640, 640, 1.0, &Device::Cpu).unwrap();
    assert_eq!(scale, 1.0, "640x640 must not be rescaled");

    let vb =
        unsafe { VarBuilder::from_mmaped_safetensors(&[weights], DType::F32, &Device::Cpu) }.unwrap();
    let craft = ffai_carmenta::craft::Craft::new(vb).unwrap();
    let ours = craft.forward(&input).unwrap().flatten_all().unwrap().to_vec1::<f32>().unwrap();

    let reference: Vec<f32> = std::fs::read(&maps_bin)
        .unwrap()
        .chunks_exact(4)
        .map(|b| f32::from_le_bytes([b[0], b[1], b[2], b[3]]))
        .collect();
    assert_eq!(ours.len(), reference.len(), "map shape mismatch");

    let (mut max_d, mut sum_d) = (0f32, 0f64);
    for (a, b) in ours.iter().zip(&reference) {
        let d = (a - b).abs();
        max_d = max_d.max(d);
        sum_d += d as f64;
    }
    let mean_d = sum_d / ours.len() as f64;
    eprintln!("craft oracle: max |d| = {max_d:.2e}, mean |d| = {mean_d:.2e}");
    assert!(max_d < 5e-3, "max abs diff {max_d} vs PyTorch reference");
    assert!(mean_d < 5e-4, "mean abs diff {mean_d} vs PyTorch reference");
}

#[test]
fn crnn_ids_match_pytorch_reference_exactly() {
    let fixture = fixtures().join("crnn_fixture.json");
    let Some(weights) = model_file("crnn-english-g2", "crnn.safetensors") else {
        eprintln!("SKIP crnn oracle: weights not in cache (run tools/carmenta_crnn_prepare.py)");
        return;
    };
    if !fixture.exists() {
        eprintln!("SKIP crnn oracle: fixture missing (run tools/carmenta_crnn_prepare.py)");
        return;
    }

    let meta: serde_json::Value =
        serde_json::from_str(&std::fs::read_to_string(&fixture).unwrap()).unwrap();
    let width = meta["width"].as_u64().unwrap() as usize;
    let expected_text = meta["text"].as_str().unwrap();
    let expected_ids: Vec<u32> =
        meta["ids"].as_array().unwrap().iter().map(|v| v.as_u64().unwrap() as u32).collect();

    let input: Vec<f32> = std::fs::read(fixtures().join(meta["input"].as_str().unwrap()))
        .unwrap()
        .chunks_exact(4)
        .map(|b| f32::from_le_bytes([b[0], b[1], b[2], b[3]]))
        .collect();
    let x = Tensor::from_vec(input, (1, 1, 64, width), &Device::Cpu).unwrap();

    let vb =
        unsafe { VarBuilder::from_mmaped_safetensors(&[weights], DType::F32, &Device::Cpu) }.unwrap();
    let crnn = ffai_carmenta::crnn::Crnn::new(vb).unwrap();
    let logits = crnn.forward(&x).unwrap();

    let ids = logits.argmax(1).unwrap().to_vec1::<u32>().unwrap();
    assert_eq!(ids, expected_ids, "per-timestep argmax must match the reference EXACTLY");

    let (text, conf) = ffai_carmenta::crnn::ctc_greedy(&logits).unwrap();
    eprintln!("crnn oracle: {text:?} (conf {conf:?})");
    assert_eq!(text, expected_text);
}

#[test]
fn parseq_ids_match_pytorch_reference() {
    let fixture = fixtures().join("parseq_fixture.json");
    let Some(weights) = model_file("parseq-tiny", "parseq-tiny.safetensors") else {
        eprintln!("SKIP parseq oracle: weights not in cache (run tools/carmenta_parseq_prepare.py)");
        return;
    };
    if !fixture.exists() {
        eprintln!("SKIP parseq oracle: fixture missing (run tools/carmenta_parseq_oracle.py)");
        return;
    }
    let meta: serde_json::Value =
        serde_json::from_str(&std::fs::read_to_string(&fixture).unwrap()).unwrap();
    let expected_text = meta["text"].as_str().unwrap();

    let input: Vec<f32> = std::fs::read(fixtures().join(meta["input"].as_str().unwrap()))
        .unwrap()
        .chunks_exact(4)
        .map(|b| f32::from_le_bytes([b[0], b[1], b[2], b[3]]))
        .collect();
    let x = Tensor::from_vec(input, (1, 3, 32, 128), &Device::Cpu).unwrap();

    let vb =
        unsafe { VarBuilder::from_mmaped_safetensors(&[weights], DType::F32, &Device::Cpu) }.unwrap();
    let parseq = ffai_carmenta::parseq::Parseq::new(vb).unwrap();
    let (text, conf) = parseq.recognize(&x).unwrap();
    eprintln!("parseq oracle: {text:?} (conf {conf:?}) vs reference {expected_text:?}");
    assert_eq!(text, expected_text, "AR-greedy decode must match the reference");
}

#[test]
fn parseq_refined_text_matches_pytorch_reference() {
    let fixture = fixtures().join("parseq_refine_fixture.json");
    let Some(weights) = model_file("parseq-tiny", "parseq-tiny.safetensors") else {
        eprintln!("SKIP parseq refine oracle: weights not cached");
        return;
    };
    if !fixture.exists() {
        eprintln!("SKIP parseq refine oracle: fixture missing");
        return;
    }
    let meta: serde_json::Value =
        serde_json::from_str(&std::fs::read_to_string(&fixture).unwrap()).unwrap();
    let input: Vec<f32> = std::fs::read(fixtures().join(meta["input"].as_str().unwrap()))
        .unwrap()
        .chunks_exact(4)
        .map(|b| f32::from_le_bytes([b[0], b[1], b[2], b[3]]))
        .collect();
    let x = Tensor::from_vec(input, (1, 3, 32, 128), &Device::Cpu).unwrap();
    let vb =
        unsafe { VarBuilder::from_mmaped_safetensors(&[weights], DType::F32, &Device::Cpu) }.unwrap();
    let parseq = ffai_carmenta::parseq::Parseq::new(vb).unwrap();
    let (text, _) = parseq.recognize(&x).unwrap();
    assert_eq!(text, meta["text"].as_str().unwrap(), "refined decode must match reference");
}

/// PP-OCRv5 mobile-det against paddle's OWN EXPORTED PROGRAM, not against a
/// re-implementation of it. The fixture is a 256x256 crop of a real page at
/// native resolution — no resize, so this also covers the preprocessing (BGR
/// channel order, ImageNet statistics) rather than only the network.
///
/// The tolerance is deliberately two-sided. Probability error catches drift in
/// the network; binarised agreement at the 0.3 threshold catches the thing that
/// actually matters, because that is the map the postprocess consumes. A port
/// can be numerically close and still segment differently.
#[test]
fn mobiledet_probability_map_matches_paddle() {
    let crop_png = fixtures().join("mobiledet_oracle_crop.png");
    let prob_st = fixtures().join("mobiledet_oracle_prob.safetensors");
    let Some(weights) = model_file("ppocrv5-mobile-det", "det-fused.safetensors") else {
        eprintln!("SKIP mobiledet oracle: fused weights not in cache \
                   (run tools/carmenta_mobiledet_fuse.py)");
        return;
    };
    if !crop_png.exists() || !prob_st.exists() {
        eprintln!("SKIP mobiledet oracle: fixtures missing \
                   (run tools/carmenta_mobiledet_oracle.py)");
        return;
    }

    let img = ffai_media::load_image(&crop_png).expect("fixture crop loads");
    assert_eq!((img.width, img.height), (256, 256));
    // Long side pinned to the native 256 so the fixture is never resampled.
    let (input, sx, sy) =
        ffai_carmenta::image::mobiledet_input(&img, 256, &Device::Cpu).unwrap();
    assert_eq!((sx, sy), (1.0, 1.0), "fixture must not be rescaled");

    let vb =
        unsafe { VarBuilder::from_mmaped_safetensors(&[weights], DType::F32, &Device::Cpu) }.unwrap();
    let det = ffai_carmenta::mobiledet::MobileDet::new(vb).unwrap();
    let ours = det.forward(&input).unwrap().flatten_all().unwrap().to_vec1::<f32>().unwrap();

    let want = candle_core::safetensors::load(&prob_st, &Device::Cpu).unwrap();
    let want = want["prob"].flatten_all().unwrap().to_vec1::<f32>().unwrap();
    assert_eq!(ours.len(), want.len(), "probability map shape mismatch");

    let (mut max_d, mut disagree) = (0f32, 0usize);
    for (a, b) in ours.iter().zip(&want) {
        max_d = max_d.max((a - b).abs());
        if (*a > 0.3) != (*b > 0.3) {
            disagree += 1;
        }
    }
    let fg = want.iter().filter(|&&p| p > 0.3).count();
    eprintln!(
        "mobiledet oracle: max|dprob| {max_d:.3e}  binarised disagreement {disagree}/{} \
         ({:.4}%)  foreground {:.2}%",
        want.len(),
        100.0 * disagree as f64 / want.len() as f64,
        100.0 * fg as f64 / want.len() as f64
    );
    assert!(fg > want.len() / 100, "fixture must contain real text, got {fg} foreground px");
    assert!(max_d < 5e-3, "probability drift vs paddle: max|dprob| {max_d:.3e}");
    assert!(
        disagree * 1000 <= want.len(),
        "binarised disagreement {disagree}/{} exceeds 0.1%",
        want.len()
    );
}

/// The DB postprocess against paddle's own `DBPostProcess` on the same
/// probability map — components, minimum-area rectangle, Vatti unclip.
///
/// The network being exact does not make the postprocess exact, and the
/// postprocess is where the boxes actually come from. Reading `processors.py`
/// got this nearly right; only running it settles whether "nearly" matters.
#[test]
fn mobiledet_boxes_match_paddle_postprocess() {
    let crop_png = fixtures().join("mobiledet_oracle_crop.png");
    let boxes_json = fixtures().join("mobiledet_oracle_boxes.json");
    let Some(weights) = model_file("ppocrv5-mobile-det", "det-fused.safetensors") else {
        eprintln!("SKIP mobiledet boxes: fused weights not in cache");
        return;
    };
    if !crop_png.exists() || !boxes_json.exists() {
        eprintln!("SKIP mobiledet boxes: fixtures missing \
                   (run tools/carmenta_mobiledet_dbref.py)");
        return;
    }

    let img = ffai_media::load_image(&crop_png).unwrap();
    let (input, sx, sy) = ffai_carmenta::image::mobiledet_input(&img, 256, &Device::Cpu).unwrap();
    let vb =
        unsafe { VarBuilder::from_mmaped_safetensors(&[weights], DType::F32, &Device::Cpu) }.unwrap();
    let det = ffai_carmenta::mobiledet::MobileDet::new(vb).unwrap();
    let prob = det.forward(&input).unwrap().flatten_all().unwrap().to_vec1::<f32>().unwrap();
    let mut ours = ffai_carmenta::mobiledet::boxes_from_probability(&prob, 256, 256, sx, sy);
    ours.sort_by_key(|b| (b.y0, b.x0));

    let meta: serde_json::Value =
        serde_json::from_str(&std::fs::read_to_string(&boxes_json).unwrap()).unwrap();
    let want: Vec<Vec<f64>> = meta["boxes"]
        .as_array()
        .unwrap()
        .iter()
        .map(|b| b.as_array().unwrap().iter().map(|v| v.as_f64().unwrap()).collect())
        .collect();

    eprintln!("mobiledet boxes: ours {} / paddle {}", ours.len(), want.len());
    for b in &ours {
        eprintln!("    ours   [{}, {}, {}, {}] score {:.4}", b.x0, b.y0, b.x1, b.y1, b.score);
    }
    for b in &want {
        eprintln!("    paddle [{}, {}, {}, {}] score {:.4}", b[0], b[1], b[2], b[3], b[4]);
    }
    assert_eq!(ours.len(), want.len(), "box count differs from the reference");

    // Matched pairwise in reading order: same map, same threshold, so the
    // regions themselves are identical and only the geometry can drift.
    for (o, w) in ours.iter().zip(&want) {
        let inter = (o.x1.min(w[2] as usize).saturating_sub(o.x0.max(w[0] as usize))) as f64
            * (o.y1.min(w[3] as usize).saturating_sub(o.y0.max(w[1] as usize))) as f64;
        let ua = ((o.x1 - o.x0) * (o.y1 - o.y0)) as f64
            + (w[2] - w[0]) * (w[3] - w[1])
            - inter;
        let iou = if ua > 0.0 { inter / ua } else { 0.0 };
        assert!(
            iou > 0.90,
            "box [{}, {}, {}, {}] vs paddle [{}, {}, {}, {}]: IoU {iou:.3}",
            o.x0, o.y0, o.x1, o.y1, w[0], w[1], w[2], w[3]
        );
        // Axis-aligned quads agree exactly; rotated ones run up to +0.047
        // high because cv2.fillPoly's fixed-point edge walk claims one extra
        // row. Cause isolated and bounded in `box_score_fast`'s docs — the
        // tolerance is the MEASURED residual, not a number picked to pass.
        assert!(
            (o.score as f64 - w[4]) > -0.005 && (o.score as f64 - w[4]) < 0.05,
            "score {:.4} vs paddle {:.4}", o.score, w[4]
        );
    }
}
