//! Per-stage oracles (mission plan §2): each net must reproduce its PyTorch
//! reference on a pinned fixture — CRAFT to numeric tolerance on the
//! region/affinity maps, CRNN to exact CTC ids.
//!
//! Fixtures are regenerated by `tools/carmenta_m_c1_prepare.py` and
//! `tools/carmenta_crnn_prepare.py`; weights are the converted safetensors in
//! the FFai cache. Both are fetched/derived artifacts, so these tests SKIP
//! (loudly) when they're absent rather than failing a fresh checkout —
//! the bench gates, not CI, are where absence would be dishonest.

use candle_core::{DType, Device, Tensor};
use candle_nn::VarBuilder;
use std::path::PathBuf;

fn fixtures() -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("../../corpora/refs/fixtures")
}

fn model_file(model: &str, file: &str) -> Option<PathBuf> {
    let p = ffai_models::cache_dir().join("models").join(model).join(file);
    p.exists().then_some(p)
}

#[test]
fn craft_maps_match_pytorch_reference() {
    let crop_png = fixtures().join("craft_crop.png");
    let maps_bin = fixtures().join("craft_maps_320x320x2_f32.bin");
    let Some(weights) = model_file("craft-mlt", "craft.safetensors") else {
        eprintln!("SKIP craft oracle: weights not in cache (run tools/carmenta_m_c1_prepare.py)");
        return;
    };
    if !crop_png.exists() || !maps_bin.exists() {
        eprintln!("SKIP craft oracle: fixtures missing (run tools/carmenta_m_c1_prepare.py)");
        return;
    }

    let img = ffai_media::load_image(&crop_png).expect("fixture crop loads");
    assert_eq!((img.width, img.height), (640, 640));
    let gray = ffai_carmenta::image::to_gray_f32(&img).unwrap();
    let (input, scale) =
        ffai_carmenta::image::craft_input(&gray, 640, 640, &Device::Cpu).unwrap();
    assert_eq!(scale, 1.0, "640x640 must not be rescaled");

    let vb =
        unsafe { VarBuilder::from_mmaped_safetensors(&[weights], DType::F32, &Device::Cpu) }.unwrap();
    let craft = ffai_carmenta::craft::Craft::new(vb).unwrap();
    let ours = craft.forward(&input).unwrap().flatten_all().unwrap().to_vec1::<f32>().unwrap();

    let reference: Vec<f32> = std::fs::read(&maps_bin)
        .unwrap()
        .chunks_exact(4)
        .map(|b| f32::from_le_bytes([b[0], b[1], b[2], b[3]]))
        .collect();
    assert_eq!(ours.len(), reference.len(), "map shape mismatch");

    let (mut max_d, mut sum_d) = (0f32, 0f64);
    for (a, b) in ours.iter().zip(&reference) {
        let d = (a - b).abs();
        max_d = max_d.max(d);
        sum_d += d as f64;
    }
    let mean_d = sum_d / ours.len() as f64;
    eprintln!("craft oracle: max |d| = {max_d:.2e}, mean |d| = {mean_d:.2e}");
    assert!(max_d < 5e-3, "max abs diff {max_d} vs PyTorch reference");
    assert!(mean_d < 5e-4, "mean abs diff {mean_d} vs PyTorch reference");
}

#[test]
fn crnn_ids_match_pytorch_reference_exactly() {
    let fixture = fixtures().join("crnn_fixture.json");
    let Some(weights) = model_file("crnn-english-g2", "crnn.safetensors") else {
        eprintln!("SKIP crnn oracle: weights not in cache (run tools/carmenta_crnn_prepare.py)");
        return;
    };
    if !fixture.exists() {
        eprintln!("SKIP crnn oracle: fixture missing (run tools/carmenta_crnn_prepare.py)");
        return;
    }

    let meta: serde_json::Value =
        serde_json::from_str(&std::fs::read_to_string(&fixture).unwrap()).unwrap();
    let width = meta["width"].as_u64().unwrap() as usize;
    let expected_text = meta["text"].as_str().unwrap();
    let expected_ids: Vec<u32> =
        meta["ids"].as_array().unwrap().iter().map(|v| v.as_u64().unwrap() as u32).collect();

    let input: Vec<f32> = std::fs::read(fixtures().join(meta["input"].as_str().unwrap()))
        .unwrap()
        .chunks_exact(4)
        .map(|b| f32::from_le_bytes([b[0], b[1], b[2], b[3]]))
        .collect();
    let x = Tensor::from_vec(input, (1, 1, 64, width), &Device::Cpu).unwrap();

    let vb =
        unsafe { VarBuilder::from_mmaped_safetensors(&[weights], DType::F32, &Device::Cpu) }.unwrap();
    let crnn = ffai_carmenta::crnn::Crnn::new(vb).unwrap();
    let logits = crnn.forward(&x).unwrap();

    let ids = logits.argmax(1).unwrap().to_vec1::<u32>().unwrap();
    assert_eq!(ids, expected_ids, "per-timestep argmax must match the reference EXACTLY");

    let (text, conf) = ffai_carmenta::crnn::ctc_greedy(&logits).unwrap();
    eprintln!("crnn oracle: {text:?} (conf {conf:?})");
    assert_eq!(text, expected_text);
}

#[test]
fn parseq_ids_match_pytorch_reference() {
    let fixture = fixtures().join("parseq_fixture.json");
    let Some(weights) = model_file("parseq-tiny", "parseq-tiny.safetensors") else {
        eprintln!("SKIP parseq oracle: weights not in cache (run tools/carmenta_parseq_prepare.py)");
        return;
    };
    if !fixture.exists() {
        eprintln!("SKIP parseq oracle: fixture missing (run tools/carmenta_parseq_oracle.py)");
        return;
    }
    let meta: serde_json::Value =
        serde_json::from_str(&std::fs::read_to_string(&fixture).unwrap()).unwrap();
    let expected_text = meta["text"].as_str().unwrap();

    let input: Vec<f32> = std::fs::read(fixtures().join(meta["input"].as_str().unwrap()))
        .unwrap()
        .chunks_exact(4)
        .map(|b| f32::from_le_bytes([b[0], b[1], b[2], b[3]]))
        .collect();
    let x = Tensor::from_vec(input, (1, 3, 32, 128), &Device::Cpu).unwrap();

    let vb =
        unsafe { VarBuilder::from_mmaped_safetensors(&[weights], DType::F32, &Device::Cpu) }.unwrap();
    let parseq = ffai_carmenta::parseq::Parseq::new(vb).unwrap();
    let (text, conf) = parseq.recognize(&x).unwrap();
    eprintln!("parseq oracle: {text:?} (conf {conf:?}) vs reference {expected_text:?}");
    assert_eq!(text, expected_text, "AR-greedy decode must match the reference");
}
