//! `sample_frames` against a real MP4.
//!
//! Skips when the corpus is absent — `corpora/clips/` is generated by
//! `tools/diana_video_corpus.py`, not vendored, so a clean checkout has none.
//!
//! Verified once against OpenCV's decode of the same file, which is what
//! Ultralytics ingests video with: **48 frames both, worst channel difference
//! 2 levels, mean absolute 0.649.** That is BT.601 rounding between two
//! YUV-to-RGB conversions, not a decode disagreement. The assertions here are
//! deliberately structural rather than a pinned checksum — a checksum would
//! break on any rounding change in the colour conversion and tell nobody
//! anything useful.

use std::path::PathBuf;

fn clip() -> Option<PathBuf> {
    let p = PathBuf::from(env!("CARGO_MANIFEST_DIR"))
        .parent()?
        .parent()?
        .join("corpora/clips/diana-video/static/static.mp4");
    p.exists().then_some(p)
}

#[test]
fn decodes_a_real_mp4() {
    let Some(p) = clip() else {
        eprintln!(
            "SKIP: no video corpus. Build it with \
             `.venv-diana/Scripts/python.exe tools/diana_video_corpus.py`"
        );
        return;
    };
    let frames = ffai_media::sample_frames(&p, 0.0).expect("decode");
    assert_eq!(frames.len(), 48, "expected the corpus clip's 48 frames");

    let f = &frames[0];
    assert_eq!(f.image.width, 428);
    assert_eq!(f.image.height, 640);
    assert_eq!(f.image.format, ffai_core::types::PixelFormat::Rgb8);
    assert_eq!(f.image.data.len(), 428 * 640 * 3, "RGB8 is width*height*3");

    // Not a blank decode. A failed decode that still produces buffers yields
    // uniform frames, which every check above would pass.
    let lo = *f.image.data.iter().min().unwrap();
    let hi = *f.image.data.iter().max().unwrap();
    assert!(hi as i32 - lo as i32 > 40, "frame looks blank: {lo}..{hi}");
}

/// `fps` samples at the rate ASKED FOR — not merely "fewer frames".
///
/// # ⚠ The previous version of this test passed while the feature was broken
///
/// It asserted `some.len() < all.len()` and nothing else. That is satisfied by
/// **any** amount of decimation, including the bug it was supposed to guard:
/// `stream_frames` computed its source rate as `time_base.den / time_base.num`,
/// but a time base is a CLOCK TICK RATE, not a frame rate. MP4 commonly uses
/// 1/12800, so asking for 1 fps computed a stride of 12800 and returned
/// **exactly one frame** from every clip in the corpus. One frame is fewer than
/// 48, so the test was green for as long as the bug existed.
///
/// It is quiet in the worst way, too: one frame is a perfectly good frame, so a
/// caller gets a plausible result rather than an error. It surfaced only when
/// Argus asked for a *window* of frames and kept receiving one.
///
/// So this now checks the RATE. The spacing assertion is the sharp one — it
/// needs no knowledge of the clip's duration and fails on any stride-shaped
/// mistake by orders of magnitude.
#[test]
fn fps_samples_at_the_rate_requested() {
    let Some(p) = clip() else {
        eprintln!("SKIP: no video corpus");
        return;
    };
    let all = ffai_media::sample_frames(&p, 0.0).expect("all");
    assert!(all.len() > 10, "need a few frames to decimate");
    let span = all.last().unwrap().timestamp - all[0].timestamp;
    assert!(
        span > 0.0,
        "frames carry no timestamps: cannot judge a rate"
    );
    eprintln!("clip: {} frames spanning {span:.3}s", all.len());

    for fps in [5.0f64, 10.0, 20.0] {
        let got = ffai_media::sample_frames(&p, fps).expect("decimate");
        assert!(!got.is_empty(), "{fps} fps returned nothing");

        // 1. SPACING: consecutive kept frames are at least one interval apart.
        //    A 12800x stride cannot fake this — it would return one frame.
        let interval = 1.0 / fps;
        for w in got.windows(2) {
            let d = w[1].timestamp - w[0].timestamp;
            assert!(
                d >= interval * 0.5,
                "{fps} fps kept frames only {d:.4}s apart (interval {interval:.4}s)"
            );
        }

        // 2. COUNT: roughly rate x duration. Generous bounds — the point is to
        //    catch an order-of-magnitude error, not to pin a frame count that a
        //    rounding change would break.
        let expected = span * fps;
        assert!(
            (got.len() as f64) >= expected * 0.5 && (got.len() as f64) <= expected * 1.5 + 2.0,
            "{fps} fps over {span:.3}s kept {} frames; expected about {expected:.1}",
            got.len()
        );

        // 3. Never more than the source has.
        assert!(got.len() <= all.len(), "{fps} fps invented frames");
        eprintln!(
            "  {fps:>4} fps -> {:>3} frames (expected ~{expected:.1})",
            got.len()
        );
    }

    // A rate above the source's keeps everything, rather than erroring or
    // duplicating.
    let over = ffai_media::sample_frames(&p, 10_000.0).expect("oversample");
    assert_eq!(
        over.len(),
        all.len(),
        "oversampling should keep every frame"
    );

    let again = ffai_media::sample_frames(&p, 5.0).expect("5 fps twice");
    let once = ffai_media::sample_frames(&p, 5.0).expect("5 fps");
    assert_eq!(once.len(), again.len(), "decimation is not deterministic");
}

/// A container we have not wired must say so, not fail obscurely.
#[test]
fn unwired_container_names_the_gap() {
    // `.mkv` USED to be the example here, and it is now wired — the assertion
    // failing is what said so. Kept pointed at a container that is still
    // genuinely absent (ASF/WMV has no published rff-format crate), because the
    // thing under test is that an unsupported extension names the supported
    // ones rather than failing blankly.
    let err = ffai_media::sample_frames(std::path::Path::new("clip.wmv"), 0.0).unwrap_err();
    let msg = err.to_string();
    assert!(msg.contains("mp4"), "should list what IS supported: {msg}");
    assert!(msg.contains("mkv"), "should list what IS supported: {msg}");
}

/// Every container we claim now decodes to the same frame count.
///
/// The MKV row is the one that matters: before the AVCC->Annex-B conversion it
/// produced 164 packets, ZERO frames and zero errors — a silent short read
/// indistinguishable from an empty video.
#[test]
fn every_wired_container_decodes() {
    let root = std::path::Path::new("../../corpora/clips/entropy-ladder");
    for (file, expect) in [
        ("cavlc_akiyo.mp4", 164),
        ("akiyo.avi", 164),
        ("akiyo.ts", 164),
        ("akiyo.mkv", 164),
    ] {
        let p = root.join(file);
        if !p.exists() {
            continue; // generated corpus; skip when absent
        }
        let n = ffai_media::sample_frames(&p, 0.0)
            .unwrap_or_else(|e| panic!("{file}: {e}"))
            .len();
        assert_eq!(n, expect, "{file} decoded {n} frames, expected {expect}");
    }
}
