//! `sample_frames` against a real MP4.
//!
//! Skips when the corpus is absent — `corpora/clips/` is generated by
//! `tools/diana_video_corpus.py`, not vendored, so a clean checkout has none.
//!
//! Verified once against OpenCV's decode of the same file, which is what
//! Ultralytics ingests video with: **48 frames both, worst channel difference
//! 2 levels, mean absolute 0.649.** That is BT.601 rounding between two
//! YUV-to-RGB conversions, not a decode disagreement. The assertions here are
//! deliberately structural rather than a pinned checksum — a checksum would
//! break on any rounding change in the colour conversion and tell nobody
//! anything useful.

use std::path::PathBuf;

fn clip() -> Option<PathBuf> {
    let p = PathBuf::from(env!("CARGO_MANIFEST_DIR"))
        .parent()?
        .parent()?
        .join("corpora/clips/diana-video/static/static.mp4");
    p.exists().then_some(p)
}

#[test]
fn decodes_a_real_mp4() {
    let Some(p) = clip() else {
        eprintln!(
            "SKIP: no video corpus. Build it with \
             `.venv-diana/Scripts/python.exe tools/diana_video_corpus.py`"
        );
        return;
    };
    let frames = ffai_media::sample_frames(&p, 0.0).expect("decode");
    assert_eq!(frames.len(), 48, "expected the corpus clip's 48 frames");

    let f = &frames[0];
    assert_eq!(f.image.width, 428);
    assert_eq!(f.image.height, 640);
    assert_eq!(f.image.format, ffai_core::types::PixelFormat::Rgb8);
    assert_eq!(f.image.data.len(), 428 * 640 * 3, "RGB8 is width*height*3");

    // Not a blank decode. A failed decode that still produces buffers yields
    // uniform frames, which every check above would pass.
    let lo = *f.image.data.iter().min().unwrap();
    let hi = *f.image.data.iter().max().unwrap();
    assert!(hi as i32 - lo as i32 > 40, "frame looks blank: {lo}..{hi}");
}

/// `fps` decimates on a fixed stride: fewer frames, and reproducibly so.
#[test]
fn fps_decimates() {
    let Some(p) = clip() else {
        eprintln!("SKIP: no video corpus");
        return;
    };
    let all = ffai_media::sample_frames(&p, 0.0).expect("all");
    let some = ffai_media::sample_frames(&p, 5.0).expect("5 fps");
    assert!(!some.is_empty(), "decimation returned nothing");
    assert!(
        some.len() < all.len(),
        "5 fps kept {} of {} — no decimation happened",
        some.len(),
        all.len()
    );
    let again = ffai_media::sample_frames(&p, 5.0).expect("5 fps twice");
    assert_eq!(some.len(), again.len(), "decimation is not deterministic");
}

/// A container we have not wired must say so, not fail obscurely.
#[test]
fn unwired_container_names_the_gap() {
    let err = ffai_media::sample_frames(std::path::Path::new("clip.mkv"), 0.0).unwrap_err();
    let msg = err.to_string();
    assert!(msg.contains("MP4"), "unhelpful error: {msg}");
}
