//! `sample_frames` against a real MP4.
//!
//! Skips when the corpus is absent — `corpora/clips/` is generated by
//! `tools/diana_video_corpus.py`, not vendored, so a clean checkout has none.
//!
//! Verified once against OpenCV's decode of the same file, which is what
//! Ultralytics ingests video with: **48 frames both, worst channel difference
//! 2 levels, mean absolute 0.649.** That is BT.601 rounding between two
//! YUV-to-RGB conversions, not a decode disagreement. The assertions here are
//! deliberately structural rather than a pinned checksum — a checksum would
//! break on any rounding change in the colour conversion and tell nobody
//! anything useful.

use std::path::PathBuf;

fn clip() -> Option<PathBuf> {
    let p = PathBuf::from(env!("CARGO_MANIFEST_DIR"))
        .parent()?
        .parent()?
        .join("corpora/clips/diana-video/static/static.mp4");
    p.exists().then_some(p)
}

#[test]
fn decodes_a_real_mp4() {
    let Some(p) = clip() else {
        eprintln!(
            "SKIP: no video corpus. Build it with \
             `.venv-diana/Scripts/python.exe tools/diana_video_corpus.py`"
        );
        return;
    };
    let frames = ffai_media::sample_frames(&p, 0.0).expect("decode");
    assert_eq!(frames.len(), 48, "expected the corpus clip's 48 frames");

    let f = &frames[0];
    assert_eq!(f.image.width, 428);
    assert_eq!(f.image.height, 640);
    assert_eq!(f.image.format, ffai_core::types::PixelFormat::Rgb8);
    assert_eq!(f.image.data.len(), 428 * 640 * 3, "RGB8 is width*height*3");

    // Not a blank decode. A failed decode that still produces buffers yields
    // uniform frames, which every check above would pass.
    let lo = *f.image.data.iter().min().unwrap();
    let hi = *f.image.data.iter().max().unwrap();
    assert!(hi as i32 - lo as i32 > 40, "frame looks blank: {lo}..{hi}");
}

/// `fps` decimates on a fixed stride: fewer frames, and reproducibly so.
#[test]
fn fps_decimates() {
    let Some(p) = clip() else {
        eprintln!("SKIP: no video corpus");
        return;
    };
    let all = ffai_media::sample_frames(&p, 0.0).expect("all");
    let some = ffai_media::sample_frames(&p, 5.0).expect("5 fps");
    assert!(!some.is_empty(), "decimation returned nothing");
    assert!(
        some.len() < all.len(),
        "5 fps kept {} of {} — no decimation happened",
        some.len(),
        all.len()
    );
    let again = ffai_media::sample_frames(&p, 5.0).expect("5 fps twice");
    assert_eq!(some.len(), again.len(), "decimation is not deterministic");
}

/// A container we have not wired must say so, not fail obscurely.
#[test]
fn unwired_container_names_the_gap() {
    // `.mkv` USED to be the example here, and it is now wired — the assertion
    // failing is what said so. Kept pointed at a container that is still
    // genuinely absent (ASF/WMV has no published rff-format crate), because the
    // thing under test is that an unsupported extension names the supported
    // ones rather than failing blankly.
    let err = ffai_media::sample_frames(std::path::Path::new("clip.wmv"), 0.0).unwrap_err();
    let msg = err.to_string();
    assert!(msg.contains("mp4"), "should list what IS supported: {msg}");
    assert!(msg.contains("mkv"), "should list what IS supported: {msg}");
}

/// Every container we claim now decodes to the same frame count.
///
/// The MKV row is the one that matters: before the AVCC->Annex-B conversion it
/// produced 164 packets, ZERO frames and zero errors — a silent short read
/// indistinguishable from an empty video.
#[test]
fn every_wired_container_decodes() {
    let root = std::path::Path::new("../../corpora/clips/entropy-ladder");
    for (file, expect) in [("cavlc_akiyo.mp4", 164), ("akiyo.avi", 164),
                           ("akiyo.ts", 164), ("akiyo.mkv", 164)] {
        let p = root.join(file);
        if !p.exists() {
            continue; // generated corpus; skip when absent
        }
        let n = ffai_media::sample_frames(&p, 0.0)
            .unwrap_or_else(|e| panic!("{file}: {e}"))
            .len();
        assert_eq!(n, expect, "{file} decoded {n} frames, expected {expect}");
    }
}
