//! Build the hash-pinned Harvard-sentences TTS corpus from the canonical
//! Columbia page. Reproducible by anyone: same HTML + same arguments produces
//! a byte-identical manifest, so a published benchmark can be re-derived from
//! the public source rather than trusted.
//!
//! ```text
//! curl -sLO https://www.cs.columbia.edu/~hgs/audio/harvard.html
//! cargo run -p ffai-bench --example prepare_harvard -- \
//!     --source harvard.html \
//!     --out corpora/texts/harvard \
//!     --manifest corpora/harvard-sentences-v1.toml \
//!     --count 200
//! ```
//!
//! The Harvard sentences (IEEE Recommended Practice for Speech Quality
//! Measurements, IEEE 297-1969, Appendix C) are 72 lists of 10 phonetically
//! balanced sentences — the standard text set for speech-quality work, in the
//! public domain. Unlike the audio corpora, the TEXTS ARE COMMITTED to the
//! repo: they are ~25 KB, they carry no license restriction, and a TTS corpus
//! whose inputs can vanish with a webpage is not pinned in any useful sense.
//! The manifest still hash-pins every file, so drift is detected either way.
//!
//! Selection takes the FIRST `count` sentences in document order — whole
//! lists, because each list is phonetically balanced on its own, and a stride
//! through lists would trade that balance for nothing.

use std::collections::BTreeMap;
use std::path::{Path, PathBuf};

fn main() -> Result<(), Box<dyn std::error::Error>> {
    let args = Args::parse()?;
    let html = std::fs::read_to_string(&args.source)?;

    // <h2>List N</h2> ... <li>Sentence.</li> — parsed positionally, in
    // document order, so the same page always yields the same corpus.
    let mut sentences: Vec<(u32, u32, String)> = Vec::new(); // (list, index, text)
    let mut list = 0u32;
    let mut index = 0u32;
    for raw_line in html.lines() {
        let line = raw_line.trim();
        if let Some(rest) = line.strip_prefix("<h2>List ") {
            let n: String = rest.chars().take_while(|c| c.is_ascii_digit()).collect();
            list = n.parse()?;
            index = 0;
        } else if let Some(rest) = line.strip_prefix("<li>") {
            let text = rest.trim_end_matches("</li>").trim();
            let text = decode_entities(text)?;
            if list == 0 {
                return Err("found a <li> before any <h2>List N</h2> header".into());
            }
            index += 1;
            sentences.push((list, index, text));
        }
    }
    println!("parsed {} sentences across {} lists", sentences.len(), list);
    if sentences.len() < args.count {
        return Err(format!(
            "asked for {} sentences but the page only yielded {} — wrong source file?",
            args.count,
            sentences.len()
        )
        .into());
    }

    std::fs::create_dir_all(&args.out)?;
    let mut rows = String::new();
    let mut total_words = 0usize;
    for (i, (list, index, text)) in sentences.iter().take(args.count).enumerate() {
        let id = format!("hvd-{list:02}-{index:02}");
        let rel = PathBuf::from(format!("{id}.txt"));
        let abs = args.out.join(&rel);
        std::fs::write(&abs, text)?;
        total_words += text.split_whitespace().count();

        let sha = ffai_bench::corpus::file_sha256(&std::fs::read(&abs)?);
        // Every 3rd clip is train, the rest holdout — the same split rule as
        // the LibriSpeech corpora: claims are measured on holdout only, and a
        // train split exists so tuning has somewhere legal to happen.
        let split = if i % 3 == 2 { "train" } else { "holdout" };

        let path = rel_from_manifest(&args.manifest, &abs);
        rows.push_str(&format!(
            "\n[[clips]]\n\
             id = \"{id}\"\n\
             path = \"{path}\"\n\
             ground_truth = \"{path}\"\n\
             class = \"clean_speech\"\n\
             split = \"{split}\"\n\
             license = \"Public domain (IEEE 297-1969 App. C)\"\n\
             sha256 = \"{sha}\"\n",
        ));
        println!("  {id:<12} {split:<8} {text}");
    }

    let manifest = format!(
        // ASCII-only header: generated manifests should survive any tool's
        // encoding assumptions.
        "# Harvard sentences (IEEE 297-1969 Appendix C) - generated by\n\
         #   cargo run -p ffai-bench --example prepare_harvard\n\
         # Source: https://www.cs.columbia.edu/~hgs/audio/harvard.html\n\
         # Public domain. TEXTS ARE COMMITTED (see prepare_harvard.rs for why);\n\
         # this manifest pins them regardless.\n\
         # For TTS, `path` IS the input and `ground_truth` IS the round-trip\n\
         # target - the same file, by construction.\n\
         # {} sentences, {} words.\n\n\
         name = \"harvard-sentences\"\n\
         version = 1\n\
         task = \"tts\"\n{rows}",
        args.count, total_words,
    );
    if let Some(parent) = args.manifest.parent() {
        std::fs::create_dir_all(parent)?;
    }
    std::fs::write(&args.manifest, manifest)?;
    println!(
        "\nwrote {} ({} sentences, {} words)",
        args.manifest.display(),
        args.count,
        total_words
    );
    Ok(())
}

/// The page uses plain ASCII with a handful of entities. Anything outside the
/// known set is an error, not a pass-through — a sentence with a raw entity
/// in it would be silently mispronounced by every engine measured on it.
fn decode_entities(text: &str) -> Result<String, Box<dyn std::error::Error>> {
    let out = text
        .replace("&amp;", "&")
        .replace("&quot;", "\"")
        .replace("&#39;", "'")
        .replace("&apos;", "'");
    if out.contains('&') || out.contains('<') || out.contains('>') {
        return Err(format!("unhandled HTML entity or markup in sentence: {out}").into());
    }
    Ok(out)
}

struct Args {
    source: PathBuf,
    out: PathBuf,
    manifest: PathBuf,
    count: usize,
}

impl Args {
    fn parse() -> Result<Self, Box<dyn std::error::Error>> {
        let mut map = BTreeMap::new();
        let argv: Vec<String> = std::env::args().skip(1).collect();
        let mut i = 0;
        while i + 1 < argv.len() {
            if let Some(key) = argv[i].strip_prefix("--") {
                map.insert(key.to_string(), argv[i + 1].clone());
                i += 2;
            } else {
                i += 1;
            }
        }
        Ok(Args {
            source: PathBuf::from(
                map.get("source")
                    .cloned()
                    .unwrap_or_else(|| "harvard.html".into()),
            ),
            out: PathBuf::from(
                map.get("out")
                    .cloned()
                    .unwrap_or_else(|| "corpora/texts/harvard".into()),
            ),
            manifest: PathBuf::from(
                map.get("manifest")
                    .cloned()
                    .unwrap_or_else(|| "corpora/harvard-sentences-v1.toml".into()),
            ),
            count: map
                .get("count")
                .map(|c| c.parse())
                .transpose()?
                .unwrap_or(200),
        })
    }
}

/// Clip paths are stored relative to the manifest's directory.
fn rel_from_manifest(manifest: &Path, target: &Path) -> String {
    let base = manifest.parent().unwrap_or(Path::new("."));
    let base: Vec<_> = base.components().collect();
    let target_components: Vec<_> = target.components().collect();
    let common = base
        .iter()
        .zip(target_components.iter())
        .take_while(|(a, b)| a == b)
        .count();
    let mut out = PathBuf::new();
    for _ in common..base.len() {
        out.push("..");
    }
    for c in &target_components[common..] {
        out.push(c.as_os_str());
    }
    out.to_string_lossy().replace('\\', "/")
}
