//! Generate Carmenta's synthetic OCR corpora — deterministic, license-free.
//!
//! The mel-fixture trick applied to pixels: text rendered from a fixed word
//! list with a seeded RNG and pinned fonts is a corpus with EXACT ground
//! truth that anyone can regenerate — no license, no download gate, no
//! account. Two corpora come out:
//!
//! - **carmenta-render-v1** — single-column printed pages (the det+rec smoke
//!   corpus), class `document_scan`.
//! - **carmenta-frames-v1** — 1280×720 dark UI/HUD-style frames with light
//!   text (the LIVE per-frame latency corpus), class `scene_text`.
//!
//! Both are single-column and strictly top-to-bottom so reading order is
//! unambiguous and the whitespace-collapsed CER comparison (`Mode::Ocr`) is
//! fair to every engine.
//!
//! ```sh
//! # fonts (pinned; fetched, never committed — see .gitignore):
//! #   DejaVu 2.37 from the dejavu-fonts GitHub release
//! cargo run -p ffai-bench --example prepare_carmenta_synth -- \
//!     --fonts corpora/fonts --out corpora
//! ```
//!
//! Determinism caveat, recorded honestly: the exact pixels depend on the
//! pinned font bytes and the fontdue version in Cargo.lock. The committed
//! manifest pins the generated bytes by SHA-256, so a regeneration under a
//! different fontdue is a *new corpus version*, not a silent drift — the
//! harness will refuse to run stale manifests against new pixels.

use ffai_bench::corpus::file_sha256;
use std::fmt::Write as _;
use std::path::{Path, PathBuf};

/// xorshift64* — the same reproducible-RNG convention Mercury's temperature
/// fallback uses. No `rand` dependency, no ambient entropy.
struct Rng(u64);
impl Rng {
    fn next(&mut self) -> u64 {
        let mut x = self.0;
        x ^= x >> 12;
        x ^= x << 25;
        x ^= x >> 27;
        self.0 = x;
        x.wrapping_mul(0x2545_F491_4F6C_DD1D)
    }
    fn below(&mut self, n: usize) -> usize {
        (self.next() % n as u64) as usize
    }
    fn chance(&mut self, pct: u64) -> bool {
        self.next() % 100 < pct
    }
}

/// Fixed vocabulary: common words, some capitalized forms, numbers, and
/// punctuation-bearing tokens, so case/digit/punctuation accuracy — the parts
/// `Mode::Ocr` deliberately scores — are all exercised.
const WORDS: &[&str] = &[
    "the",
    "quick",
    "brown",
    "fox",
    "jumps",
    "over",
    "lazy",
    "dog",
    "and",
    "then",
    "walks",
    "north",
    "toward",
    "harbour",
    "lights",
    "while",
    "morning",
    "traffic",
    "builds",
    "along",
    "river",
    "road",
    "seven",
    "small",
    "boats",
    "carry",
    "fresh",
    "catch",
    "market",
    "stalls",
    "open",
    "early",
    "vendors",
    "arrange",
    "crates",
    "apples",
    "pears",
    "plums",
    "under",
    "canvas",
    "awnings",
    "children",
    "watch",
    "gulls",
    "circle",
    "above",
    "pier",
    "old",
    "clock",
    "tower",
    "strikes",
    "quarter",
    "hour",
    "ferry",
    "departs",
    "exactly",
    "schedule",
    "passengers",
    "read",
    "papers",
    "coffee",
    "steam",
    "rises",
    "from",
    "paper",
    "cups",
    "signal",
    "changes",
    "green",
    "trucks",
    "roll",
    "forward",
    "past",
    "warehouse",
    "doors",
    "painted",
    "blue",
    "numbers",
    "stencilled",
    "white",
    "letters",
    "faded",
    "sun",
    "rain",
    "wind",
    "salt",
    "air",
    "keeps",
    "everything",
    "honest",
    "measured",
    "recorded",
    "ledger",
];

const CAPS: &[&str] = &[
    "Mercury",
    "Carmenta",
    "Argus",
    "Whisper",
    "Tesseract",
    "Rust",
    "Monday",
    "October",
];

const NUMBERS: &[&str] = &[
    "1274", "38.2", "07:45", "2026", "500", "16", "99.5%", "$42", "No. 7", "3rd",
];

/// HUD-style short lines for the frames corpus.
const HUD: &[&str] = &[
    "REC 00:12:47",
    "FPS 59.94",
    "CPU 34% MEM 183 MiB",
    "SPEAKER_00 active",
    "LIVE — Channel 7 News",
    "Battery 82% remaining",
    "ALT 1240 m HDG 274",
    "Download 96.5% complete",
    "Lap 12 of 44 — P3",
    "Uptime 14d 07:45:12",
    "Queue depth 512 items",
    "Bitrate 6.2 Mbps stable",
];

struct Fonts {
    sans: fontdue::Font,
    serif: fontdue::Font,
    mono: fontdue::Font,
}

struct Canvas {
    w: usize,
    h: usize,
    buf: Vec<u8>,
}

impl Canvas {
    fn new(w: usize, h: usize, bg: u8) -> Self {
        Canvas {
            w,
            h,
            buf: vec![bg; w * h],
        }
    }

    /// Draw one line of text at (x, baseline). Returns the advance in px.
    fn draw_text(
        &mut self,
        font: &fontdue::Font,
        text: &str,
        px: f32,
        x: f32,
        baseline: f32,
        fg: u8,
    ) -> f32 {
        let mut cursor = x;
        for ch in text.chars() {
            let (m, bitmap) = font.rasterize(ch, px);
            let gx = (cursor + m.xmin as f32) as i64;
            let gy = baseline as i64 - (m.height as i64 + m.ymin as i64);
            for row in 0..m.height {
                for col in 0..m.width {
                    let (tx, ty) = (gx + col as i64, gy + row as i64);
                    if tx < 0 || ty < 0 || tx >= self.w as i64 || ty >= self.h as i64 {
                        continue;
                    }
                    let a = bitmap[row * m.width + col] as f32 / 255.0;
                    let dst = &mut self.buf[ty as usize * self.w + tx as usize];
                    *dst = (*dst as f32 * (1.0 - a) + fg as f32 * a).round() as u8;
                }
            }
            cursor += m.advance_width;
        }
        cursor - x
    }

    fn width_of(font: &fontdue::Font, text: &str, px: f32) -> f32 {
        text.chars()
            .map(|c| font.metrics(c, px).advance_width)
            .sum()
    }

    fn save_png(&self, path: &Path) -> std::io::Result<()> {
        let file = std::fs::File::create(path)?;
        let mut enc =
            png::Encoder::new(std::io::BufWriter::new(file), self.w as u32, self.h as u32);
        enc.set_color(png::ColorType::Grayscale);
        enc.set_depth(png::BitDepth::Eight);
        let mut writer = enc.write_header()?;
        writer.write_image_data(&self.buf)?;
        Ok(())
    }
}

fn word(rng: &mut Rng) -> String {
    if rng.chance(6) {
        CAPS[rng.below(CAPS.len())].to_string()
    } else if rng.chance(7) {
        NUMBERS[rng.below(NUMBERS.len())].to_string()
    } else {
        WORDS[rng.below(WORDS.len())].to_string()
    }
}

fn sentence(rng: &mut Rng) -> String {
    let n = 6 + rng.below(9);
    let mut s = String::new();
    for i in 0..n {
        let mut w = word(rng);
        if i == 0 {
            let mut chars = w.chars();
            if let Some(first) = chars.next() {
                w = first.to_uppercase().collect::<String>() + chars.as_str();
            }
        }
        if !s.is_empty() {
            s.push(' ');
        }
        s.push_str(&w);
        if i + 1 < n && rng.chance(8) {
            s.push(',');
        }
    }
    s.push(match rng.below(10) {
        0 => '?',
        1 => '!',
        _ => '.',
    });
    s
}

/// Render one printed page. Returns (canvas, ground truth).
fn render_page(fonts: &Fonts, rng: &mut Rng) -> (Canvas, String) {
    let (w, h, margin) = (816usize, 1056usize, 72.0f32);
    let mut canvas = Canvas::new(w, h, 255);
    let font = if rng.chance(50) {
        &fonts.serif
    } else {
        &fonts.sans
    };
    let px = [17.0, 20.0, 23.0, 27.0][rng.below(4)];
    let line_h = px * 1.45;
    let mut truth = String::new();
    let mut y = margin + px;

    let paragraphs = 3 + rng.below(3);
    'pages: for p in 0..paragraphs {
        let sentences = 2 + rng.below(4);
        let mut para = String::new();
        for _ in 0..sentences {
            if !para.is_empty() {
                para.push(' ');
            }
            para.push_str(&sentence(rng));
        }
        // Word-wrap inside the margins; stop the page before the bottom one.
        // Ground truth accumulates PER DRAWN WORD, never per planned
        // paragraph: a page that fills mid-paragraph must not leave pixels
        // the truth doesn't cover (or truth the pixels don't) — either way
        // every engine's error rate would carry the corpus's own defect.
        if p > 0 {
            truth.push_str("\n\n");
        }
        let mut x = margin;
        let mut first_in_para = true;
        for wtoken in para.split(' ') {
            let adv = Canvas::width_of(font, wtoken, px);
            if x + adv > w as f32 - margin {
                x = margin;
                y += line_h;
                if y > h as f32 - margin {
                    break 'pages;
                }
            }
            canvas.draw_text(font, wtoken, px, x, y, 20);
            x += adv + Canvas::width_of(font, " ", px);
            if !first_in_para {
                truth.push(' ');
            }
            truth.push_str(wtoken);
            first_in_para = false;
        }
        y += line_h * 1.8;
        if y > h as f32 - margin {
            break;
        }
    }
    (canvas, truth.trim_end().to_string())
}

/// Render one HUD/UI-style frame. Returns (canvas, ground truth).
fn render_frame(fonts: &Fonts, rng: &mut Rng) -> (Canvas, String) {
    let (w, h) = (1280usize, 720usize);
    let mut canvas = Canvas::new(w, h, 28);
    let font = if rng.chance(60) {
        &fonts.mono
    } else {
        &fonts.sans
    };
    let mut truth = String::new();

    let lines = 4 + rng.below(4);
    let mut used = Vec::new();
    let mut y = 60.0;
    for _ in 0..lines {
        // Distinct lines per frame, strictly top-to-bottom.
        let mut idx = rng.below(HUD.len());
        while used.contains(&idx) {
            idx = rng.below(HUD.len());
        }
        used.push(idx);
        let text = if rng.chance(30) {
            sentence(rng)
        } else {
            HUD[idx].to_string()
        };
        let px = [19.0, 22.0, 26.0][rng.below(3)];
        canvas.draw_text(font, &text, px, 64.0, y, 235);
        if !truth.is_empty() {
            truth.push('\n');
        }
        truth.push_str(&text);
        y += 90.0 + rng.below(20) as f32;
    }
    (canvas, truth)
}

struct Args {
    fonts: PathBuf,
    out: PathBuf,
}

fn parse_args() -> Args {
    let mut fonts = PathBuf::from("corpora/fonts");
    let mut out = PathBuf::from("corpora");
    let argv: Vec<String> = std::env::args().collect();
    let mut i = 1;
    while i < argv.len() {
        match argv[i].as_str() {
            "--fonts" => {
                fonts = PathBuf::from(&argv[i + 1]);
                i += 2;
            }
            "--out" => {
                out = PathBuf::from(&argv[i + 1]);
                i += 2;
            }
            other => {
                eprintln!("unknown arg `{other}` (expected --fonts DIR, --out DIR)");
                std::process::exit(2);
            }
        }
    }
    Args { fonts, out }
}

fn main() {
    let args = parse_args();
    let load = |name: &str| {
        let bytes = std::fs::read(args.fonts.join(name)).unwrap_or_else(|e| {
            panic!(
                "reading {name} from {}: {e} — fetch DejaVu 2.37 first (see module docs)",
                args.fonts.display()
            )
        });
        fontdue::Font::from_bytes(bytes, fontdue::FontSettings::default()).expect("font parses")
    };
    let fonts = Fonts {
        sans: load("DejaVuSans.ttf"),
        serif: load("DejaVuSerif.ttf"),
        mono: load("DejaVuSansMono.ttf"),
    };

    generate_docs(&fonts, &args.out);

    // (corpus name, clip prefix, count, class, generator)
    type Gen = fn(&Fonts, &mut Rng) -> (Canvas, String);
    let specs: [(&str, &str, usize, &str, Gen); 2] = [
        ("carmenta-render", "page", 24, "document_scan", render_page),
        ("carmenta-frames", "frame", 30, "scene_text", render_frame),
    ];

    for (corpus, prefix, count, class, generate) in specs {
        // Seed fixed per corpus: regeneration reproduces the exact content.
        let mut rng = Rng(0x00C0FFEE ^ corpus.len() as u64);
        let clip_dir = args.out.join("clips").join(corpus);
        std::fs::create_dir_all(&clip_dir).expect("mkdir clips");

        let mut manifest = String::new();
        writeln!(manifest, "name = \"{corpus}\"").unwrap();
        writeln!(manifest, "version = 1").unwrap();
        writeln!(manifest, "task = \"ocr\"").unwrap();

        for i in 0..count {
            let (canvas, truth) = generate(&fonts, &mut rng);
            let id = format!("{prefix}-{i:02}");
            let png_rel = format!("clips/{corpus}/{id}.png");
            let txt_rel = format!("clips/{corpus}/{id}.txt");
            canvas
                .save_png(&args.out.join(&png_rel))
                .expect("write png");
            std::fs::write(args.out.join(&txt_rel), &truth).expect("write gt");
            let sha = file_sha256(&std::fs::read(args.out.join(&png_rel)).unwrap());
            // Every 4th clip is train; claims run on the holdout rest.
            let split = if i % 4 == 3 { "train" } else { "holdout" };
            writeln!(manifest).unwrap();
            writeln!(manifest, "[[clips]]").unwrap();
            writeln!(manifest, "id = \"{id}\"").unwrap();
            writeln!(manifest, "path = \"{png_rel}\"").unwrap();
            writeln!(manifest, "ground_truth = \"{txt_rel}\"").unwrap();
            writeln!(manifest, "class = \"{class}\"").unwrap();
            writeln!(manifest, "split = \"{split}\"").unwrap();
            writeln!(
                manifest,
                "license = \"CC0-1.0 (synthetic, generated by prepare_carmenta_synth)\""
            )
            .unwrap();
            writeln!(manifest, "sha256 = \"{sha}\"").unwrap();
        }

        let manifest_path = args.out.join(format!("{corpus}-v1.toml"));
        std::fs::write(&manifest_path, manifest).expect("write manifest");
        println!("wrote {} ({count} clips)", manifest_path.display());
    }

    generate_screencast(&fonts, &args.out);
}

/// carmenta-screencast-v1: the LIVE corpus — one continuous 180-frame
/// sequence (60 s at 3 fps) of a HUD whose six text slots change at known
/// frames, plus ±1-level deterministic per-pixel noise so no two frames are
/// byte-identical (a change gate that only survives byte-equality is not a
/// change gate). Ground truth includes WHEN text changed, which makes this
/// corpus the stability oracle: between changes, output churn is a defect.
///
/// All frames are holdout — the stream is one measurement and splitting it
/// would break continuity. Tuning space is the frames corpus's train split.
fn generate_screencast(fonts: &Fonts, out: &std::path::Path) {
    const FRAMES: usize = 180;
    const SLOTS: usize = 6;
    let corpus = "carmenta-screencast";
    let clip_dir = out.join("clips").join(corpus);
    std::fs::create_dir_all(&clip_dir).expect("mkdir screencast");

    // Slot i changes every `period[i]` frames, staggered so changes rarely
    // coincide; content is drawn deterministically from the HUD pool + the
    // sentence generator.
    let periods = [23usize, 31, 41, 53, 67, 79];
    let mut rng = Rng(0xC0FFEE_5EED);
    let mut slot_text: Vec<String> = (0..SLOTS).map(|_| String::new()).collect();
    let ys = [60.0, 170.0, 280.0, 390.0, 500.0, 610.0];

    let mut manifest = String::new();
    writeln!(manifest, "name = \"{corpus}\"").unwrap();
    writeln!(manifest, "version = 1").unwrap();
    writeln!(manifest, "task = \"ocr\"").unwrap();
    let mut changes = Vec::new();

    for f in 0..FRAMES {
        let mut changed = false;
        for s in 0..SLOTS {
            if f % periods[s] == 0 {
                slot_text[s] = if rng.chance(60) {
                    HUD[rng.below(HUD.len())].to_string()
                } else {
                    sentence(&mut rng)
                };
                changed = true;
            }
        }
        if changed {
            changes.push(f);
        }

        let mut canvas = Canvas::new(1280, 720, 28);
        for s in 0..SLOTS {
            canvas.draw_text(&fonts.mono, &slot_text[s], 22.0, 64.0, ys[s], 235);
        }
        // Deterministic per-frame noise, ±1 level: below the change gate's
        // threshold, above byte-equality.
        let mut noise = Rng(0x0BAD_5EED ^ f as u64);
        for px in canvas.buf.iter_mut() {
            let n = (noise.next() % 3) as i16 - 1;
            *px = (*px as i16 + n).clamp(0, 255) as u8;
        }

        let id = format!("sc-{f:03}");
        let png_rel = format!("clips/{corpus}/{id}.png");
        let txt_rel = format!("clips/{corpus}/{id}.txt");
        canvas.save_png(&out.join(&png_rel)).expect("write frame");
        std::fs::write(out.join(&txt_rel), slot_text.join("\n")).expect("write gt");
        let sha = file_sha256(&std::fs::read(out.join(&png_rel)).unwrap());
        writeln!(manifest).unwrap();
        writeln!(manifest, "[[clips]]").unwrap();
        writeln!(manifest, "id = \"{id}\"").unwrap();
        writeln!(manifest, "path = \"{png_rel}\"").unwrap();
        writeln!(manifest, "ground_truth = \"{txt_rel}\"").unwrap();
        writeln!(manifest, "class = \"video\"").unwrap();
        writeln!(manifest, "split = \"holdout\"").unwrap();
        writeln!(
            manifest,
            "license = \"CC0-1.0 (synthetic, generated by prepare_carmenta_synth)\""
        )
        .unwrap();
        writeln!(manifest, "sha256 = \"{sha}\"").unwrap();
    }

    let manifest_path = out.join(format!("{corpus}-v1.toml"));
    std::fs::write(&manifest_path, manifest).expect("write manifest");
    // The change timeline, for the stability oracle: which frames changed.
    let timeline = changes
        .iter()
        .map(|f| f.to_string())
        .collect::<Vec<_>>()
        .join(",");
    std::fs::write(clip_dir.join("changes.csv"), timeline).expect("write timeline");
    println!(
        "wrote {} ({FRAMES} frames, {} change events)",
        manifest_path.display(),
        changes.len()
    );
}

// ---------------------------------------------------------------------------
// carmenta-doc-v1 — the DOCUMENT corpus (M-C3), and LONG's seed (M-C4)
// ---------------------------------------------------------------------------
//
// M-C3 gates on reading-order accuracy AND end-to-end CER, and nothing we had
// could carry both. §8.17 measured why the obvious candidate could not:
// DocLayNet ships full pages at 1025x1025, so a body line is 9-12 px, and
// EVERY engine lands near 50 % CER there — PaddleOCR at 53.94 % — which makes
// it an instrument for layout and not for reading. Upscaling was refuted
// across a 3.5x sweep; resampling does not restore information a 9-px glyph
// never had.
//
// So this renders its own, at 1700x2200 (letter at ~200 dpi) where body text
// is ~28 px. Rendering rather than collecting buys four things a public set
// cannot: exact reading order, exact region boxes, arbitrary resolution, and
// CONTROLLED SKEW — §8.24 measured a 1.26 pp prize for perspective-warped
// crops and had to park it because no corpus had any skew to fail on.
//
// The text is synthesised from the same fixed lexicon as the other two
// corpora, not drawn from Gutenberg. That is deliberate and worth stating: a
// downloaded book would add a fetch gate to a corpus whose whole point is that
// anyone can regenerate it from a formula, and a controlled vocabulary keeps
// out-of-vocabulary surprises from confounding a measurement about LAYOUT.
//
// Documents are split whole. A document whose pages straddle train and holdout
// would leak across the split the moment M-C4 starts consuming `doc_id`.

/// One laid-out region, with its place in the reading order.
struct Region {
    class: &'static str,
    order: usize,
    /// Corners, clockwise from top-left. Axis-aligned unless the page is
    /// skewed, which is why this is a quad and not a rect.
    quad: [(f32, f32); 4],
    text: String,
}

impl Region {
    fn boxed(class: &'static str, order: usize, b: (f32, f32, f32, f32), text: String) -> Self {
        Region {
            class,
            order,
            quad: [(b.0, b.1), (b.2, b.1), (b.2, b.3), (b.0, b.3)],
            text,
        }
    }
}

const DOC_W: usize = 1700;
const DOC_H: usize = 2200;
const DOC_MARGIN: f32 = 130.0;

fn doc_sentence(rng: &mut Rng, words: usize) -> String {
    let mut s = String::new();
    for i in 0..words {
        if i > 0 {
            s.push(' ');
        }
        let w = word(rng);
        if i == 0 {
            let mut c = w.chars();
            if let Some(f) = c.next() {
                s.extend(f.to_uppercase());
                s.push_str(c.as_str());
            }
        } else {
            s.push_str(&w);
        }
    }
    s.push('.');
    s
}

/// Word-wrap `text` into a column and draw it. Returns the region's box and the
/// text actually drawn — which is not always the text asked for, because a
/// column can run out before a paragraph does, and truth must follow PIXELS.
#[allow(clippy::too_many_arguments)]
fn draw_column_block(
    canvas: &mut Canvas,
    font: &fontdue::Font,
    text: &str,
    px: f32,
    x0: f32,
    y: &mut f32,
    col_w: f32,
    bottom: f32,
) -> Option<((f32, f32, f32, f32), String)> {
    let line_h = px * 1.42;
    if *y + line_h > bottom {
        return None;
    }
    let top = *y - px;
    let (mut cx, mut drawn, mut first) = (x0, String::new(), true);
    for tok in text.split(' ') {
        let adv = Canvas::width_of(font, tok, px);
        if cx + adv > x0 + col_w {
            cx = x0;
            *y += line_h;
            if *y + 0.25 * px > bottom {
                *y -= line_h;
                break;
            }
        }
        canvas.draw_text(font, tok, px, cx, *y, 20);
        cx += adv + Canvas::width_of(font, " ", px);
        if !first {
            drawn.push(' ');
        }
        drawn.push_str(tok);
        first = false;
    }
    if drawn.is_empty() {
        return None;
    }
    let bbox = (x0, top, x0 + col_w, *y + 0.28 * px);
    *y += line_h * 1.55;
    Some((bbox, drawn))
}

/// Rotate a canvas about its centre, sampling bilinearly on a white ground.
fn rotate_canvas(src: &Canvas, deg: f32) -> Canvas {
    let mut dst = Canvas::new(src.w, src.h, 255);
    let (cx, cy) = (src.w as f32 / 2.0, src.h as f32 / 2.0);
    let (s, c) = (-deg.to_radians()).sin_cos();
    for y in 0..dst.h {
        for x in 0..dst.w {
            let (dx, dy) = (x as f32 - cx, y as f32 - cy);
            let (sx, sy) = (c * dx - s * dy + cx, s * dx + c * dy + cy);
            if sx < 0.0 || sy < 0.0 || sx >= src.w as f32 - 1.0 || sy >= src.h as f32 - 1.0 {
                continue;
            }
            let (x0, y0) = (sx.floor() as usize, sy.floor() as usize);
            let (fx, fy) = (sx - x0 as f32, sy - y0 as f32);
            let p = |xx: usize, yy: usize| src.buf[yy * src.w + xx] as f32;
            let v = p(x0, y0) * (1.0 - fx) * (1.0 - fy)
                + p(x0 + 1, y0) * fx * (1.0 - fy)
                + p(x0, y0 + 1) * (1.0 - fx) * fy
                + p(x0 + 1, y0 + 1) * fx * fy;
            dst.buf[y * dst.w + x] = v.round() as u8;
        }
    }
    dst
}

/// Forward-rotate a point the same way `rotate_canvas` moves the pixels.
fn rotate_pt(p: (f32, f32), deg: f32, cx: f32, cy: f32) -> (f32, f32) {
    let (s, c) = deg.to_radians().sin_cos();
    let (dx, dy) = (p.0 - cx, p.1 - cy);
    (c * dx - s * dy + cx, s * dx + c * dy + cy)
}

/// Render one page. Returns its regions in reading order.
fn render_doc_page(
    fonts: &Fonts,
    rng: &mut Rng,
    doc_title: &str,
    page_no: usize,
    two_col: bool,
) -> (Canvas, Vec<Region>) {
    let mut canvas = Canvas::new(DOC_W, DOC_H, 255);
    let mut regions: Vec<Region> = Vec::new();
    let mut order = 0usize;

    let bottom = DOC_H as f32 - DOC_MARGIN - 60.0;
    let mut y = DOC_MARGIN + 30.0;

    // Running header on every page but the first — the classic thing a LONG
    // pipeline has to learn to suppress across pages.
    if page_no > 0 {
        let t = doc_title.to_string();
        let w = Canvas::width_of(&fonts.sans, &t, 22.0);
        canvas.draw_text(&fonts.sans, &t, 22.0, DOC_MARGIN, y, 90);
        regions.push(Region::boxed(
            "page-header",
            order,
            (DOC_MARGIN, y - 22.0, DOC_MARGIN + w, y + 6.0),
            t,
        ));
        order += 1;
        y += 60.0;
    } else {
        let w = Canvas::width_of(&fonts.serif, doc_title, 52.0);
        canvas.draw_text(&fonts.serif, doc_title, 52.0, DOC_MARGIN, y + 40.0, 10);
        regions.push(Region::boxed(
            "title",
            order,
            (DOC_MARGIN, y - 12.0, DOC_MARGIN + w, y + 54.0),
            doc_title.to_string(),
        ));
        order += 1;
        y += 130.0;
    }

    // Body. A two-column page lays out the LEFT column completely, then the
    // right — which is exactly the reading order a raster-order reader gets
    // wrong, and the reason this corpus exists.
    let usable = DOC_W as f32 - 2.0 * DOC_MARGIN;
    let (cols, col_w) = if two_col {
        (2usize, (usable - 60.0) / 2.0)
    } else {
        (1usize, usable)
    };
    let col_top = if page_no == 0 {
        DOC_MARGIN + 160.0
    } else {
        DOC_MARGIN + 90.0
    };
    for col in 0..cols {
        let x0 = DOC_MARGIN + col as f32 * (col_w + 60.0);
        let mut cy = if col == 0 { y } else { col_top };
        while cy < bottom {
            if rng.chance(4) {
                let nw = 2 + rng.below(3);
                let h = doc_sentence(rng, nw);
                let h = h.trim_end_matches('.').to_string();
                match draw_column_block(
                    &mut canvas,
                    &fonts.sans,
                    &h,
                    30.0,
                    x0,
                    &mut cy,
                    col_w,
                    bottom,
                ) {
                    Some((b, t)) => {
                        regions.push(Region::boxed("section-header", order, b, t));
                        order += 1;
                    }
                    None => break,
                }
            }
            let is_list = rng.chance(5);
            let body = if is_list {
                {
                    let nw = 6 + rng.below(8);
                    format!("- {}", doc_sentence(rng, nw))
                }
            } else {
                let mut p = String::new();
                for i in 0..(2 + rng.below(3)) {
                    if i > 0 {
                        p.push(' ');
                    }
                    let nw = 8 + rng.below(12);
                    p.push_str(&doc_sentence(rng, nw));
                }
                p
            };
            match draw_column_block(
                &mut canvas,
                &fonts.serif,
                &body,
                26.0,
                x0,
                &mut cy,
                col_w,
                bottom,
            ) {
                Some((b, t)) => {
                    regions.push(Region::boxed(
                        if is_list { "list-item" } else { "text" },
                        order,
                        b,
                        t,
                    ));
                    order += 1;
                }
                None => break,
            }
        }
    }

    let foot = format!("Page {}", page_no + 1);
    let fw = Canvas::width_of(&fonts.sans, &foot, 22.0);
    let fx = (DOC_W as f32 - fw) / 2.0;
    let fy = DOC_H as f32 - DOC_MARGIN + 20.0;
    canvas.draw_text(&fonts.sans, &foot, 22.0, fx, fy, 90);
    regions.push(Region::boxed(
        "page-footer",
        order,
        (fx, fy - 22.0, fx + fw, fy + 6.0),
        foot,
    ));

    (canvas, regions)
}

fn generate_docs(fonts: &Fonts, out: &Path) {
    const DOCS: usize = 8;
    const PAGES: usize = 4;
    let clip_dir = out.join("clips").join("carmenta-doc");
    std::fs::create_dir_all(&clip_dir).expect("mkdir doc clips");

    let mut manifest = String::new();
    writeln!(manifest, "name = \"carmenta-doc\"").unwrap();
    writeln!(manifest, "version = 1").unwrap();
    writeln!(manifest, "task = \"ocr\"").unwrap();
    writeln!(manifest).unwrap();

    let mut rng = Rng(0x0D0C_5EED);
    let mut n = 0usize;
    for doc in 0..DOCS {
        let title = format!("{} Report No. {}", CAPS[doc % CAPS.len()], 1200 + doc * 37);
        // Columns and skew are CROSSED, not correlated — a 2x2 with two
        // documents per cell. The first cut tied them together (`doc % 2` for
        // both), and the corpus duly separated 0.40 % from 71.61 % while being
        // unable to say WHICH variable did it. A corpus that cannot attribute
        // is half-built.
        let two_col = (doc / 2) % 2 == 1;
        let skew = if doc % 2 == 1 {
            0.8 + (doc as f32) * 0.4
        } else {
            0.0
        };
        // Documents split WHOLE — one straddling the split would leak the
        // moment M-C4 groups pages by `doc_id` — and each split gets one
        // document from every cell, so neither is missing a condition.
        let split = if doc < 4 { "train" } else { "holdout" };
        for page in 0..PAGES {
            let (canvas, mut regions) = render_doc_page(fonts, &mut rng, &title, page, two_col);
            let canvas = if skew > 0.0 {
                let (cx, cy) = (DOC_W as f32 / 2.0, DOC_H as f32 / 2.0);
                for r in &mut regions {
                    for p in &mut r.quad {
                        *p = rotate_pt(*p, skew, cx, cy);
                    }
                }
                rotate_canvas(&canvas, skew)
            } else {
                canvas
            };

            let stem = format!("doc-{n:03}");
            canvas
                .save_png(&clip_dir.join(format!("{stem}.png")))
                .expect("write page");
            regions.sort_by_key(|r| r.order);
            let truth: String = regions
                .iter()
                .map(|r| r.text.as_str())
                .collect::<Vec<_>>()
                .join("\n");
            std::fs::write(clip_dir.join(format!("{stem}.txt")), &truth).expect("write truth");

            let mut js = String::from("{\n");
            writeln!(
                js,
                " \"doc_id\": \"doc-{doc:02}\", \"page\": {page}, \"n_pages\": {PAGES},"
            )
            .unwrap();
            writeln!(
                js,
                " \"columns\": {}, \"skew_deg\": {skew:.2},",
                if two_col { 2 } else { 1 }
            )
            .unwrap();
            writeln!(js, " \"page_size\": [{DOC_W}, {DOC_H}],").unwrap();
            writeln!(js, " \"regions\": [").unwrap();
            for (i, r) in regions.iter().enumerate() {
                let q: Vec<String> = r
                    .quad
                    .iter()
                    .map(|p| format!("[{:.1},{:.1}]", p.0, p.1))
                    .collect();
                writeln!(
                    js,
                    "  {{\"order\": {}, \"class\": \"{}\", \"quad\": [{}], \"text\": {:?}}}{}",
                    r.order,
                    r.class,
                    q.join(","),
                    r.text,
                    if i + 1 == regions.len() { "" } else { "," }
                )
                .unwrap();
            }
            js.push_str(" ]\n}\n");
            std::fs::write(clip_dir.join(format!("{stem}.json")), js).expect("write layout");

            let sha = file_sha256(&std::fs::read(clip_dir.join(format!("{stem}.png"))).unwrap());
            writeln!(manifest, "[[clips]]").unwrap();
            writeln!(manifest, "id = \"{stem}\"").unwrap();
            writeln!(manifest, "path = \"clips/carmenta-doc/{stem}.png\"").unwrap();
            writeln!(manifest, "ground_truth = \"clips/carmenta-doc/{stem}.txt\"").unwrap();
            // `class` is a closed enum in the corpus schema; the 1- vs
            // 2-column split lives in the JSON sidecar, which is where the
            // layout ground truth belongs anyway.
            writeln!(manifest, "class = \"document_scan\"").unwrap();
            writeln!(manifest, "split = \"{split}\"").unwrap();
            writeln!(
                manifest,
                "license = \"synthetic (CC0) — regenerate with prepare_carmenta_synth\""
            )
            .unwrap();
            writeln!(manifest, "sha256 = \"{sha}\"").unwrap();
            writeln!(manifest).unwrap();
            n += 1;
        }
    }
    std::fs::write(out.join("carmenta-doc-v1.toml"), manifest).expect("write doc manifest");
    println!(
        "carmenta-doc: {n} pages across {DOCS} documents -> {}",
        clip_dir.display()
    );
}
