//! Generate Carmenta's synthetic OCR corpora — deterministic, license-free.
//!
//! The mel-fixture trick applied to pixels: text rendered from a fixed word
//! list with a seeded RNG and pinned fonts is a corpus with EXACT ground
//! truth that anyone can regenerate — no license, no download gate, no
//! account. Two corpora come out:
//!
//! - **carmenta-render-v1** — single-column printed pages (the det+rec smoke
//!   corpus), class `document_scan`.
//! - **carmenta-frames-v1** — 1280×720 dark UI/HUD-style frames with light
//!   text (the LIVE per-frame latency corpus), class `scene_text`.
//!
//! Both are single-column and strictly top-to-bottom so reading order is
//! unambiguous and the whitespace-collapsed CER comparison (`Mode::Ocr`) is
//! fair to every engine.
//!
//! ```sh
//! # fonts (pinned; fetched, never committed — see .gitignore):
//! #   DejaVu 2.37 from the dejavu-fonts GitHub release
//! cargo run -p ffai-bench --example prepare_carmenta_synth -- \
//!     --fonts corpora/fonts --out corpora
//! ```
//!
//! Determinism caveat, recorded honestly: the exact pixels depend on the
//! pinned font bytes and the fontdue version in Cargo.lock. The committed
//! manifest pins the generated bytes by SHA-256, so a regeneration under a
//! different fontdue is a *new corpus version*, not a silent drift — the
//! harness will refuse to run stale manifests against new pixels.

use ffai_bench::corpus::file_sha256;
use std::fmt::Write as _;
use std::path::{Path, PathBuf};

/// xorshift64* — the same reproducible-RNG convention Mercury's temperature
/// fallback uses. No `rand` dependency, no ambient entropy.
struct Rng(u64);
impl Rng {
    fn next(&mut self) -> u64 {
        let mut x = self.0;
        x ^= x >> 12;
        x ^= x << 25;
        x ^= x >> 27;
        self.0 = x;
        x.wrapping_mul(0x2545_F491_4F6C_DD1D)
    }
    fn below(&mut self, n: usize) -> usize {
        (self.next() % n as u64) as usize
    }
    fn chance(&mut self, pct: u64) -> bool {
        self.next() % 100 < pct
    }
}

/// Fixed vocabulary: common words, some capitalized forms, numbers, and
/// punctuation-bearing tokens, so case/digit/punctuation accuracy — the parts
/// `Mode::Ocr` deliberately scores — are all exercised.
const WORDS: &[&str] = &[
    "the", "quick", "brown", "fox", "jumps", "over", "lazy", "dog", "and", "then", "walks",
    "north", "toward", "harbour", "lights", "while", "morning", "traffic", "builds", "along",
    "river", "road", "seven", "small", "boats", "carry", "fresh", "catch", "market", "stalls",
    "open", "early", "vendors", "arrange", "crates", "apples", "pears", "plums", "under",
    "canvas", "awnings", "children", "watch", "gulls", "circle", "above", "pier", "old",
    "clock", "tower", "strikes", "quarter", "hour", "ferry", "departs", "exactly", "schedule",
    "passengers", "read", "papers", "coffee", "steam", "rises", "from", "paper", "cups",
    "signal", "changes", "green", "trucks", "roll", "forward", "past", "warehouse", "doors",
    "painted", "blue", "numbers", "stencilled", "white", "letters", "faded", "sun", "rain",
    "wind", "salt", "air", "keeps", "everything", "honest", "measured", "recorded", "ledger",
];

const CAPS: &[&str] = &["Mercury", "Carmenta", "Argus", "Whisper", "Tesseract", "Rust", "Monday", "October"];

const NUMBERS: &[&str] = &["1274", "38.2", "07:45", "2026", "500", "16", "99.5%", "$42", "No. 7", "3rd"];

/// HUD-style short lines for the frames corpus.
const HUD: &[&str] = &[
    "REC 00:12:47",
    "FPS 59.94",
    "CPU 34% MEM 183 MiB",
    "SPEAKER_00 active",
    "LIVE — Channel 7 News",
    "Battery 82% remaining",
    "ALT 1240 m HDG 274",
    "Download 96.5% complete",
    "Lap 12 of 44 — P3",
    "Uptime 14d 07:45:12",
    "Queue depth 512 items",
    "Bitrate 6.2 Mbps stable",
];

struct Fonts {
    sans: fontdue::Font,
    serif: fontdue::Font,
    mono: fontdue::Font,
}

struct Canvas {
    w: usize,
    h: usize,
    buf: Vec<u8>,
}

impl Canvas {
    fn new(w: usize, h: usize, bg: u8) -> Self {
        Canvas { w, h, buf: vec![bg; w * h] }
    }

    /// Draw one line of text at (x, baseline). Returns the advance in px.
    fn draw_text(&mut self, font: &fontdue::Font, text: &str, px: f32, x: f32, baseline: f32, fg: u8) -> f32 {
        let mut cursor = x;
        for ch in text.chars() {
            let (m, bitmap) = font.rasterize(ch, px);
            let gx = (cursor + m.xmin as f32) as i64;
            let gy = baseline as i64 - (m.height as i64 + m.ymin as i64);
            for row in 0..m.height {
                for col in 0..m.width {
                    let (tx, ty) = (gx + col as i64, gy + row as i64);
                    if tx < 0 || ty < 0 || tx >= self.w as i64 || ty >= self.h as i64 {
                        continue;
                    }
                    let a = bitmap[row * m.width + col] as f32 / 255.0;
                    let dst = &mut self.buf[ty as usize * self.w + tx as usize];
                    *dst = (*dst as f32 * (1.0 - a) + fg as f32 * a).round() as u8;
                }
            }
            cursor += m.advance_width;
        }
        cursor - x
    }

    fn width_of(font: &fontdue::Font, text: &str, px: f32) -> f32 {
        text.chars().map(|c| font.metrics(c, px).advance_width).sum()
    }

    fn save_png(&self, path: &Path) -> std::io::Result<()> {
        let file = std::fs::File::create(path)?;
        let mut enc = png::Encoder::new(std::io::BufWriter::new(file), self.w as u32, self.h as u32);
        enc.set_color(png::ColorType::Grayscale);
        enc.set_depth(png::BitDepth::Eight);
        let mut writer = enc.write_header()?;
        writer.write_image_data(&self.buf)?;
        Ok(())
    }
}

fn word(rng: &mut Rng) -> String {
    if rng.chance(6) {
        CAPS[rng.below(CAPS.len())].to_string()
    } else if rng.chance(7) {
        NUMBERS[rng.below(NUMBERS.len())].to_string()
    } else {
        WORDS[rng.below(WORDS.len())].to_string()
    }
}

fn sentence(rng: &mut Rng) -> String {
    let n = 6 + rng.below(9);
    let mut s = String::new();
    for i in 0..n {
        let mut w = word(rng);
        if i == 0 {
            let mut chars = w.chars();
            if let Some(first) = chars.next() {
                w = first.to_uppercase().collect::<String>() + chars.as_str();
            }
        }
        if !s.is_empty() {
            s.push(' ');
        }
        s.push_str(&w);
        if i + 1 < n && rng.chance(8) {
            s.push(',');
        }
    }
    s.push(match rng.below(10) {
        0 => '?',
        1 => '!',
        _ => '.',
    });
    s
}

/// Render one printed page. Returns (canvas, ground truth).
fn render_page(fonts: &Fonts, rng: &mut Rng) -> (Canvas, String) {
    let (w, h, margin) = (816usize, 1056usize, 72.0f32);
    let mut canvas = Canvas::new(w, h, 255);
    let font = if rng.chance(50) { &fonts.serif } else { &fonts.sans };
    let px = [17.0, 20.0, 23.0, 27.0][rng.below(4)];
    let line_h = px * 1.45;
    let mut truth = String::new();
    let mut y = margin + px;

    let paragraphs = 3 + rng.below(3);
    'pages: for p in 0..paragraphs {
        let sentences = 2 + rng.below(4);
        let mut para = String::new();
        for _ in 0..sentences {
            if !para.is_empty() {
                para.push(' ');
            }
            para.push_str(&sentence(rng));
        }
        // Word-wrap inside the margins; stop the page before the bottom one.
        // Ground truth accumulates PER DRAWN WORD, never per planned
        // paragraph: a page that fills mid-paragraph must not leave pixels
        // the truth doesn't cover (or truth the pixels don't) — either way
        // every engine's error rate would carry the corpus's own defect.
        if p > 0 {
            truth.push_str("\n\n");
        }
        let mut x = margin;
        let mut first_in_para = true;
        for wtoken in para.split(' ') {
            let adv = Canvas::width_of(font, wtoken, px);
            if x + adv > w as f32 - margin {
                x = margin;
                y += line_h;
                if y > h as f32 - margin {
                    break 'pages;
                }
            }
            canvas.draw_text(font, wtoken, px, x, y, 20);
            x += adv + Canvas::width_of(font, " ", px);
            if !first_in_para {
                truth.push(' ');
            }
            truth.push_str(wtoken);
            first_in_para = false;
        }
        y += line_h * 1.8;
        if y > h as f32 - margin {
            break;
        }
    }
    (canvas, truth.trim_end().to_string())
}

/// Render one HUD/UI-style frame. Returns (canvas, ground truth).
fn render_frame(fonts: &Fonts, rng: &mut Rng) -> (Canvas, String) {
    let (w, h) = (1280usize, 720usize);
    let mut canvas = Canvas::new(w, h, 28);
    let font = if rng.chance(60) { &fonts.mono } else { &fonts.sans };
    let mut truth = String::new();

    let lines = 4 + rng.below(4);
    let mut used = Vec::new();
    let mut y = 60.0;
    for _ in 0..lines {
        // Distinct lines per frame, strictly top-to-bottom.
        let mut idx = rng.below(HUD.len());
        while used.contains(&idx) {
            idx = rng.below(HUD.len());
        }
        used.push(idx);
        let text = if rng.chance(30) { sentence(rng) } else { HUD[idx].to_string() };
        let px = [19.0, 22.0, 26.0][rng.below(3)];
        canvas.draw_text(font, &text, px, 64.0, y, 235);
        if !truth.is_empty() {
            truth.push('\n');
        }
        truth.push_str(&text);
        y += 90.0 + rng.below(20) as f32;
    }
    (canvas, truth)
}

struct Args {
    fonts: PathBuf,
    out: PathBuf,
}

fn parse_args() -> Args {
    let mut fonts = PathBuf::from("corpora/fonts");
    let mut out = PathBuf::from("corpora");
    let argv: Vec<String> = std::env::args().collect();
    let mut i = 1;
    while i < argv.len() {
        match argv[i].as_str() {
            "--fonts" => {
                fonts = PathBuf::from(&argv[i + 1]);
                i += 2;
            }
            "--out" => {
                out = PathBuf::from(&argv[i + 1]);
                i += 2;
            }
            other => {
                eprintln!("unknown arg `{other}` (expected --fonts DIR, --out DIR)");
                std::process::exit(2);
            }
        }
    }
    Args { fonts, out }
}

fn main() {
    let args = parse_args();
    let load = |name: &str| {
        let bytes = std::fs::read(args.fonts.join(name))
            .unwrap_or_else(|e| panic!("reading {name} from {}: {e} — fetch DejaVu 2.37 first (see module docs)", args.fonts.display()));
        fontdue::Font::from_bytes(bytes, fontdue::FontSettings::default()).expect("font parses")
    };
    let fonts = Fonts {
        sans: load("DejaVuSans.ttf"),
        serif: load("DejaVuSerif.ttf"),
        mono: load("DejaVuSansMono.ttf"),
    };

    // (corpus name, clip prefix, count, class, generator)
    type Gen = fn(&Fonts, &mut Rng) -> (Canvas, String);
    let specs: [(&str, &str, usize, &str, Gen); 2] = [
        ("carmenta-render", "page", 24, "document_scan", render_page),
        ("carmenta-frames", "frame", 30, "scene_text", render_frame),
    ];

    for (corpus, prefix, count, class, generate) in specs {
        // Seed fixed per corpus: regeneration reproduces the exact content.
        let mut rng = Rng(0x00C0FFEE ^ corpus.len() as u64);
        let clip_dir = args.out.join("clips").join(corpus);
        std::fs::create_dir_all(&clip_dir).expect("mkdir clips");

        let mut manifest = String::new();
        writeln!(manifest, "name = \"{corpus}\"").unwrap();
        writeln!(manifest, "version = 1").unwrap();
        writeln!(manifest, "task = \"ocr\"").unwrap();

        for i in 0..count {
            let (canvas, truth) = generate(&fonts, &mut rng);
            let id = format!("{prefix}-{i:02}");
            let png_rel = format!("clips/{corpus}/{id}.png");
            let txt_rel = format!("clips/{corpus}/{id}.txt");
            canvas.save_png(&args.out.join(&png_rel)).expect("write png");
            std::fs::write(args.out.join(&txt_rel), &truth).expect("write gt");
            let sha = file_sha256(&std::fs::read(args.out.join(&png_rel)).unwrap());
            // Every 4th clip is train; claims run on the holdout rest.
            let split = if i % 4 == 3 { "train" } else { "holdout" };
            writeln!(manifest).unwrap();
            writeln!(manifest, "[[clips]]").unwrap();
            writeln!(manifest, "id = \"{id}\"").unwrap();
            writeln!(manifest, "path = \"{png_rel}\"").unwrap();
            writeln!(manifest, "ground_truth = \"{txt_rel}\"").unwrap();
            writeln!(manifest, "class = \"{class}\"").unwrap();
            writeln!(manifest, "split = \"{split}\"").unwrap();
            writeln!(manifest, "license = \"CC0-1.0 (synthetic, generated by prepare_carmenta_synth)\"").unwrap();
            writeln!(manifest, "sha256 = \"{sha}\"").unwrap();
        }

        let manifest_path = args.out.join(format!("{corpus}-v1.toml"));
        std::fs::write(&manifest_path, manifest).expect("write manifest");
        println!("wrote {} ({count} clips)", manifest_path.display());
    }

    generate_screencast(&fonts, &args.out);
}

/// carmenta-screencast-v1: the LIVE corpus — one continuous 180-frame
/// sequence (60 s at 3 fps) of a HUD whose six text slots change at known
/// frames, plus ±1-level deterministic per-pixel noise so no two frames are
/// byte-identical (a change gate that only survives byte-equality is not a
/// change gate). Ground truth includes WHEN text changed, which makes this
/// corpus the stability oracle: between changes, output churn is a defect.
///
/// All frames are holdout — the stream is one measurement and splitting it
/// would break continuity. Tuning space is the frames corpus's train split.
fn generate_screencast(fonts: &Fonts, out: &std::path::Path) {
    const FRAMES: usize = 180;
    const SLOTS: usize = 6;
    let corpus = "carmenta-screencast";
    let clip_dir = out.join("clips").join(corpus);
    std::fs::create_dir_all(&clip_dir).expect("mkdir screencast");

    // Slot i changes every `period[i]` frames, staggered so changes rarely
    // coincide; content is drawn deterministically from the HUD pool + the
    // sentence generator.
    let periods = [23usize, 31, 41, 53, 67, 79];
    let mut rng = Rng(0xC0FFEE_5EED);
    let mut slot_text: Vec<String> = (0..SLOTS).map(|_| String::new()).collect();
    let ys = [60.0, 170.0, 280.0, 390.0, 500.0, 610.0];

    let mut manifest = String::new();
    writeln!(manifest, "name = \"{corpus}\"").unwrap();
    writeln!(manifest, "version = 1").unwrap();
    writeln!(manifest, "task = \"ocr\"").unwrap();
    let mut changes = Vec::new();

    for f in 0..FRAMES {
        let mut changed = false;
        for s in 0..SLOTS {
            if f % periods[s] == 0 {
                slot_text[s] = if rng.chance(60) {
                    HUD[rng.below(HUD.len())].to_string()
                } else {
                    sentence(&mut rng)
                };
                changed = true;
            }
        }
        if changed {
            changes.push(f);
        }

        let mut canvas = Canvas::new(1280, 720, 28);
        for s in 0..SLOTS {
            canvas.draw_text(&fonts.mono, &slot_text[s], 22.0, 64.0, ys[s], 235);
        }
        // Deterministic per-frame noise, ±1 level: below the change gate's
        // threshold, above byte-equality.
        let mut noise = Rng(0x0BAD_5EED ^ f as u64);
        for px in canvas.buf.iter_mut() {
            let n = (noise.next() % 3) as i16 - 1;
            *px = (*px as i16 + n).clamp(0, 255) as u8;
        }

        let id = format!("sc-{f:03}");
        let png_rel = format!("clips/{corpus}/{id}.png");
        let txt_rel = format!("clips/{corpus}/{id}.txt");
        canvas.save_png(&out.join(&png_rel)).expect("write frame");
        std::fs::write(out.join(&txt_rel), slot_text.join("\n")).expect("write gt");
        let sha = file_sha256(&std::fs::read(out.join(&png_rel)).unwrap());
        writeln!(manifest).unwrap();
        writeln!(manifest, "[[clips]]").unwrap();
        writeln!(manifest, "id = \"{id}\"").unwrap();
        writeln!(manifest, "path = \"{png_rel}\"").unwrap();
        writeln!(manifest, "ground_truth = \"{txt_rel}\"").unwrap();
        writeln!(manifest, "class = \"video\"").unwrap();
        writeln!(manifest, "split = \"holdout\"").unwrap();
        writeln!(manifest, "license = \"CC0-1.0 (synthetic, generated by prepare_carmenta_synth)\"").unwrap();
        writeln!(manifest, "sha256 = \"{sha}\"").unwrap();
    }

    let manifest_path = out.join(format!("{corpus}-v1.toml"));
    std::fs::write(&manifest_path, manifest).expect("write manifest");
    // The change timeline, for the stability oracle: which frames changed.
    let timeline = changes.iter().map(|f| f.to_string()).collect::<Vec<_>>().join(",");
    std::fs::write(clip_dir.join("changes.csv"), timeline).expect("write timeline");
    println!("wrote {} ({FRAMES} frames, {} change events)", manifest_path.display(), changes.len());
}
